language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn compile
- yarn test
before_deploy:
- npm version from-git
- cp README.md package.json dist/
- cd dist
deploy:
  provider: npm
  email: m.helmich@mittwald.de
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: lm9NpuuA1rT6naKuYyjtZU0KnSyly/svm4cCa0BZJ475wJ4St0uKXonbRF6187waw5ACxAAR3XOYCGg6vQfp70eql6V4K8VECwKax5Ojds03SqNbw9r/JdrAHJUV+6RnPxuoqS4OsJ0HwZE7OsQFpEE8cTc1g4Y+lPXcZwBXCVNRvWUZWXJwULfEM0aANK3HPdHYkqwdVGRyx0cHnVKUbj/cYOfs2i42OpdCsTDDSdPjeg2R0PpPuo7mvUN+R79tRcy5dXvRBCcOt3BrP+D5dTt8gPpwaUYBNkYHt/9B/meKpN+a+z8lsjlrCe89QxkSD79fR9B/tXwo5mlrDVwdi4DudFD7K4axQkNWx6QP+jH0thnkqYIzuvOQE4dCoWmVBMUAiMpAb0XeZQaU5MbaLT0+T+aIjylm3HjETZ925l1HUakQylwBnB6+tKSZk0Ohz0QpVkwkFBsFmE9DvkBcI5HJHwcHVmNPu9d/E8n5PvV+Xs5/7+9GrQaxpfW97Bh4hNcZDXvif+gGOzJNusQu84YZLa53FUrorf9u8CFAnOZgzp2x3bXR0nX2KdYtz34kuH1YEN2EivZmoWCRUPF8I9nH96gBjY+KVSd83vOb1Kja3EwS9HI/EisGEhoqKJu/9awX+0lEsEDYAE/9oltbP+UskO1/skgrerbP630iLac=
